---
# Satellite Settings
satellite_server_url: "satellite.fqdn" # string
satellite_username: "admin" # Username for Red Hat Satellite Administration
satellite_password: "changeme" # Best Practice: Store satellite_password in a vault
satellite_organization: "Default Organization"

# Optional Variables with defaults
satellite_validate_certs: false    # boolean
satellite_operation_timeout: 7200  # 2 hours in seconds, integer
satellite_poll_interval: 30        # 30 seconds, integer
satellite_max_retries: 3           # 3 attempts, integer
satellite_retry_delay: 30          # 30 seconds, integer
satellite_export_wait_time: 21600  # 21600 seconds == 6 hours

# Export Settings
satellite_timestamp: "{{ ansible_date_time['date'] }}"
satellite_directories: "/var/lib/pulp"
satellite_export_library: true # boolean, default false
satellite_export_lock_file: "/tmp/satellite-export.lock"
satellite_export_history: true
satellite_required_space_gb: 500 # integer, set to number in GB; 2000 GB == 2 TB
satellite_cleanup_old_exports: true # Default set to true, reduces the amount of content view exports
satellite_cleanup_old_export_age: "30d" # Default to 30 days, format is integer/string 1w == 1 week / 1d == 1 day
satellite_export_library_format: importable # syncable or importable
satellite_export_destination_server_fqdn: "" # Destination server name; optional parameter to differentiate between exports
satellite_export_library_incremental: false
satellite_export_library_fail_on_missing_content: true # boolean, default true, fails if any of the repositories belonging to this version are unexportable
...
