---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Configure Puppet repositories
      ansible.builtin.include_role:
        name: theforeman.operations.puppet_repositories
    - name: Configure Foreman repositories  # noqa: var-naming[pattern]
      ansible.builtin.include_role:
        name: theforeman.operations.foreman_repositories
      vars:
        foreman_repositories_version: "3.16"
        foreman_repositories_katello_version: "4.18"
