---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Install satellite-installer RPM
      ansible.builtin.package:
        name: satellite-installer
        state: present

    - name: Find satellite-installer symlink
      ansible.builtin.stat:
        path: /usr/sbin/satellite-installer
      register: satellite_installer

    - name: Check satellite-installer symlink exists
      ansible.builtin.assert:
        that:
          - satellite_installer.stat.exists
          - satellite_installer.stat.islnk
