namespace: "redhat"
name: "satellite_operations"
description: Satellite operations tasks such as install, upgrade and maintenance
authors:
  - "Baptiste Agasse <bagasse@redhat.com>"
  - "Eric D. Helms <ericdhelms@gmail.com>"
  - "Evgeni Golov <evgeni@golov.de>"
  - "Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl>"
  - "Jeffrey van Pelt <jeff@vanpelt.one>"
  - "Kyle Williams <kyle.williams@thetradedesk.com>"
  - "Matthias Dellweg <2500@gmx.de>"
  - "willtome <willtome@gmail.com>"
version: "1.0.2"
license:
  - "GPL-3.0-or-later"
tags:
  - foreman
  - katello
  - satellite
  - infrastructure
readme: "README.md"
homepage: "https://access.redhat.com/products/red-hat-satellite"
repository: "https://github.com/RedHatSatellite/satellite-operations-collection"
documentation: "https://access.redhat.com/documentation/en-us/red_hat_satellite/"
issues: "https://bugzilla.redhat.com"
