namespace: "redhat"
name: "satellite-operations"
description: Satellite operations tasks such as install, upgrade and maintenance
authors:
 - "Eric D. Helms <ericdhelms@gmail.com>"
 - "Evgeni Golov <evgeni@golov.de>"
 - "Matthias Dellweg <2500@gmx.de>"
 - "willtome <willtome@gmail.com>"
version: "0.3.0"
license:
  - "GPL-3.0-or-later"
tags:
  - foreman
  - katello
  - satellite
readme: "README.md"
homepage: "https://access.redhat.com/products/red-hat-satellite"
repository: "https://github.com/RedHatSatellite/satellite-operations-collection"
documentation: "https://access.redhat.com/documentation/en-us/red_hat_satellite/"
issues: "https://bugzilla.redhat.com"
