---
- name: Certificate | Create Satellite certificate directory
  ansible.builtin.file:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}"
    state: directory

- name: Certificate | Generate server private key
  community.crypto.openssl_privatekey:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_key.pem"
    size: 4096

- name: Certificate | Check for existing CSR
  ansible.builtin.stat:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem"
  register: existing_csr

- name: Certificate | Generate CNF file
  ansible.builtin.template:
    src: openssl.cnf.j2
    dest: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_openssl.cnf"

- name: Certificate | Generate CSR file
  ansible.builtin.shell: "openssl req -new -key /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_key.pem -out /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem -config /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_openssl.cnf"
  when:
    - not existing_csr['stat']['exists']

# - name: Certificate | Wait for CSR signing
#   ansible.builtin.pause:
#     prompt: "CSR is located at /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem, please sign. Place cert at /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert.pem, place the CA bundle at /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_bundle.pem"
#   when:
#     - not existing_csr['stat']['exists']

# - name: Certificate | Test certificate
#   ansible.builtin.shell: "katello-certs-check -c /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert.pem -k /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_key.pem -b /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_bundle.pem"
#   register: katello_cert_check
#   check_mode: false
#   changed_when: false

# - name: Certificate | Print certificate check
#   ansible.builtin.debug:
#     msg: "{{ katello_cert_check['stdout_lines'] }}"
...
