---
- name: Enabling repos | Checking pulp directory is owned by pulp
  ansible.builtin.file:
    path: /var/lib/pulp
    owner: pulp
    group: pulp
    mode: '0775'

- name: Enable repos | Enable Red Hat repos
  redhat.satellite.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    label: "{{ item['label'] }}"
    repositories: "{{ item['repos'] | default(omit) }}"
    all_repositories: "{{ item['all'] | default(omit) }}"
    state: enabled
    validate_certs: "{{ satellite_validate_certs }}"
  loop: "{{ satellite_redhat_repos }}"
...
