---
- name: Install rpmbuild and dependencies
  package:
    name:
      - rpm-build
      - createrepo
      - rpmdevtools

- name: Create directory structure for rpmbuild
  shell: rpmdev-setuptree  # noqa command-instead-of-shell
  args:
    creates: "{{ ansible_env.HOME }}/rpmbuild"

- name: Copy spec file to destination
  template:
    src: satellite-installer.spec.j2
    dest: "{{ ansible_env.HOME }}/rpmbuild/SPECS/satellite-installer.spec"
    mode: 0644

- name: Build satellite-installer RPM
  shell: "rpmbuild -ba SPECS/satellite-installer.spec"  # noqa command-instead-of-shell
  args:
    chdir: "{{ ansible_env.HOME }}/rpmbuild"
  register: build_result
  changed_when: true
  tags:
    - molecule-idempotence-notest

- name: Copy satellite-installer RPM to local repo
  copy:
    src: "{{ ansible_env.HOME }}/rpmbuild/RPMS/x86_64/"
    dest: "{{ fake_installer_rpm_repo }}"
    remote_src: true
    mode: 0644
  tags:
    - molecule-idempotence-notest

- name: Create a local repository
  command: "createrepo --update {{ fake_installer_rpm_repo }}"
  changed_when: true
  tags:
    - molecule-idempotence-notest

- name: Create yumrepo
  yum_repository:
    name: fake-installer-rpm
    description: Local repository for satellite-installer fake RPM
    baseurl: "file://{{ fake_installer_rpm_repo }}"
    enabled: true
    gpgcheck: false
