---
- name: Check that necessary variables are defined
  ansible.builtin.assert:
    that:
      - satellite_installer_scenario is defined

# This is a workaround for https://projects.theforeman.org/issues/34468
- name: "Install hostname"
  ansible.builtin.package:
    name: hostname
    state: present

- name: "Install {{ satellite_installer_package }}"
  ansible.builtin.package:
    name: "{{ satellite_installer_package }}"
    state: present

- name: Run installer
  ansible.builtin.command: >
    {{ satellite_installer_command }}
    --scenario {{ satellite_installer_scenario }}
    {{ (satellite_installer_verbose | bool) | ternary("-v", "") }}
    {{ (satellite_installer_no_colors | bool) | ternary("--no-colors", "") }}
    {{ satellite_installer_options | join(' ') }}
    --detailed-exitcodes
  async: "{{ ansible_check_mode | ternary(0, satellite_installer_timeout) }}"  # avoid connection timeouts
  changed_when: false  # async always returns changed, check in async_status instead
  poll: 0
  register: __satellite_installer_async_results
  environment:
    LC_ALL: "{{ satellite_installer_locale }}"
    LANG: "{{ satellite_installer_locale }}"

- name: Check async status for satellite-installer
  ansible.builtin.async_status:
    jid: "{{ __satellite_installer_async_results.ansible_job_id }}"
  register: __satellite_installer_async_poll_results
  until: __satellite_installer_async_poll_results.finished
  changed_when: __satellite_installer_async_poll_results.rc is defined and __satellite_installer_async_poll_results.rc == 2
  failed_when:
    - (not __satellite_installer_async_poll_results.finished) or (__satellite_installer_async_poll_results.rc is defined and __satellite_installer_async_poll_results.rc not in [0, 2])
  retries: "{{ ((satellite_installer_timeout | int) / 5) | round | int }}"
  delay: 5
  when:
    - not ansible_check_mode
