---
- name: Check that necessary variables are defined
  assert:
    that:
      - satellite_installer_scenario is defined

- name: "Install {{ satellite_installer_package }}"
  package:
    name: "{{ satellite_installer_package }}"
    state: present

- name: 'Run installer'
  command: >
    {{ satellite_installer_command }}
    --scenario {{ satellite_installer_scenario }}
    {{ (satellite_installer_verbose|bool) | ternary("-v", "") }}
    {{ (satellite_installer_no_colors|bool) | ternary("--no-colors", "") }}
    {{ satellite_installer_options | join(' ') }}
    --detailed-exitcodes
  register: satellite_installer_run
  changed_when: satellite_installer_run.rc == 2
  failed_when: satellite_installer_run.rc not in [0, 2]
