---
- name: Check that necessary variables are defined
  assert:
    that:
      - satellite_installer_scenario is defined

- when:
    - ansible_distribution_major_version == '8'
    - ansible_os_family == 'RedHat'
  block:
    - name: Get satellite-installer version
      dnf:
        list: satellite-installer
      register: package_info

    - name: Enable ruby:2.7 module
      dnf:
        name: '@ruby:2.7'
        state: present
      when:
        - (package_info.results | map(attribute='version') | max) is version("2.5", ">=")

# This is a workaround for https://projects.theforeman.org/issues/34468
- name: "Install hostname"
  package:
    name: hostname
    state: present

- name: "Install {{ satellite_installer_package }}"
  package:
    name: "{{ satellite_installer_package }}"
    state: present

- name: Run installer
  command: >
    {{ satellite_installer_command }}
    --scenario {{ satellite_installer_scenario }}
    {{ (satellite_installer_verbose|bool) | ternary("-v", "") }}
    {{ (satellite_installer_no_colors|bool) | ternary("--no-colors", "") }}
    {{ satellite_installer_options | join(' ') }}
    --detailed-exitcodes
  async: "{{ ansible_check_mode | ternary(0, satellite_installer_timeout) }}"  # avoid connection timeouts
  changed_when: false  # async always returns changed, check in async_status instead
  poll: 0
  register: async_results
  environment:
    LC_ALL: "{{ satellite_installer_locale }}"
    LANG: "{{ satellite_installer_locale }}"

- name: Check async status for satellite-installer
  async_status:
    jid: "{{ async_results.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  changed_when: async_poll_results.rc is defined and async_poll_results.rc == 2
  failed_when:
    - (not async_poll_results.finished) or (async_poll_results.rc is defined and async_poll_results.rc not in [0, 2])
  retries: "{{ ((satellite_installer_timeout | int) / 5) | round | int }}"
  delay: 5
  when:
    - not ansible_check_mode
