---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    satellite_installer_scenario: satellite
  roles:
    - role: installer
      vars:
        satellite_installer_options:
          - '--foreman-initial-organization "Test Org"'
          - '--tuning development'
    - role: installer
      vars:
        satellite_installer_options:
          - '--enable-foreman-plugin-tasks'
          - '--tuning development'
