---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    satellite_installer_scenario: satellite
  roles:
    - role: installer
      vars:
        satellite_installer_options:
          - '--disable-system-checks'
    - role: installer
      vars:
        satellite_installer_options:
          - '--enable-foreman-plugin-tasks'
          - '--disable-system-checks'
