---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    satellite_installer_scenario: foreman
  roles:
    - role: installer
    - role: installer
      vars:
        satellite_installer_options:
          - '--enable-foreman-plugin-tasks'
