---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  vars:
    foreman_repositories_version: '2.4'
  roles:
    - theforeman.operations.puppet_repositories
    - theforeman.operations.foreman_repositories
    - fake_installer_rpm
