---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  vars:
    foreman_repositories_version: "3.2"
    foreman_repositories_katello_version: "4.4"
  roles:
    - theforeman.operations.puppet_repositories
    - theforeman.operations.foreman_repositories
    - fake_installer_rpm
  tasks:
    - name: Ensure langpacks on EL8
      dnf:
        name: glibc-langpack-en
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
