---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  roles:
    - theforeman.operations.puppet_repositories
    - role: theforeman.operations.foreman_repositories
      vars:
        foreman_repositories_version: "3.2"
        foreman_repositories_katello_version: "4.4"
    - fake_installer_rpm
  tasks:
    - name: Ensure langpacks on EL8
      ansible.builtin.dnf:
        name: glibc-langpack-en
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
