---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  vars:
    foreman_repositories_version: "3.1"
    foreman_repositories_katello_version: "4.3"
  roles:
    - theforeman.operations.foreman_repositories
    - theforeman.operations.puppet_repositories
    - fake_installer_rpm
  post_tasks:
    - name: Ensure langpacks on EL8
      dnf:
        name: glibc-langpack-en
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: run installer
      include_role:
        name: installer
      vars:
        satellite_installer_scenario: satellite
        satellite_installer_options:
          - '--disable-system-checks'
          - '--verbose-log-level debug'
