---
- name: Install PCP and optional PMDAs
  ansible.builtin.package:
    name: "{{ ['foreman-pcp', 'pcp'] + satellite_metrics_pcp_additional_packages + satellite_metrics_pcp_optional_agent_packages }}"
    state: present
    disable_plugin: "{{ 'foreman-protector' if ansible_os_family == 'RedHat' else omit }}"

- name: Read pmcd.conf
  ansible.builtin.slurp:
    src: /etc/pcp/pmcd/pmcd.conf
  register: __satellite_pmcd_conf

# see https://pcp.readthedocs.io/en/latest/UAG/InstallingAndConfiguringPcp.html#managing-optional-pmdas
- name: Ensure optional metric collection agents are enabled
  ansible.builtin.file:
    path: "/var/lib/pcp/pmdas/{{ item }}/.NeedInstall"
    mode: u=rw,g=r,o=r
    state: touch
  vars:
    __satellite_pmcd_enabled_pmdas: "{{ __satellite_pmcd_conf['content'] | b64decode | split('\n') | select('contains', 'pcp/pmdas') | map('split') | map('first') }}"
  loop: "{{ satellite_metrics_pcp_optional_agents }}"
  when: item not in __satellite_pmcd_enabled_pmdas
  notify:
    - Restart pmcd
    - Restart pmproxy
    - Restart pmlogger

- name: Configure OpenMetrics PMDA to read Satellite metrics
  ansible.builtin.copy:
    dest: /var/lib/pcp/pmdas/openmetrics/config.d/foreman.url
    content: "{{ satellite_metrics_url }}"
    mode: '0644'
  notify:
    - Restart pmcd
    - Restart pmproxy
    - Restart pmlogger

- name: Configure hotproc PMDA to monitor Satellite processes
  ansible.builtin.file:
    path: /var/lib/pcp/pmdas/proc/hotproc.conf
    src: /etc/pcp/proc/foreman-hotproc.conf
    state: link
  notify:
    - Restart pmcd
    - Restart pmproxy
    - Restart pmlogger

- name: Enable pmcd
  ansible.builtin.service:
    name: pmcd
    state: started
    enabled: true

- name: Enable pmproxy
  ansible.builtin.service:
    name: pmproxy
    state: started
    enabled: true

- name: Enable pmlogger
  ansible.builtin.service:
    name: pmlogger
    state: started
    enabled: true

- name: Enable pmie
  ansible.builtin.service:
    name: pmie
    state: started
    enabled: true

- name: Include Grafana tasks
  ansible.builtin.include_tasks: grafana.yml
  when: satellite_metrics_grafana_enabled
