name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'RedHatSatellite/satellite-operations-collection'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ansible
        run: pip install --upgrade ansible
      - name: Build Ansible Collection
        run: make dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: redhat-satellite_operations-*.tar.gz
