---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get cronjob file
      ansible.builtin.slurp:
        path: /etc/cron.daily/foreman-backup
      register: __satellite_backupcron

    - name: Check foreman cronjob content
      ansible.builtin.assert:
        that:
          - "'/var/backup/foreman' in __satellite_crobjobcontent"
      vars:
        __satellite_crobjobcontent: "{{ __satellite_backupcron['content'] | b64decode }}"
